import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 30,
    justifyContent:"center"
  },
  label: {
    textTransform: "uppercase",
    fontSize: 16,
    color: "#6b7a82",
    marginBottom: 10,
    marginLeft: 4,
    alignSelf: "flex-start",
    fontWeight: "500",
    letterSpacing: 0.5,
  },
  formInputs: {
    borderColor: "#10A78B",
    borderWidth: 1,
    height: 45,
    borderRadius: 12,
    width: "100%",
    paddingHorizontal: 10,
    backgroundColor: "#10A78B",
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 10,
  },
  formInputs2: {
    borderColor: "#10A78B",
    borderWidth: 1,
    height: 45,
    borderRadius: 12,
    width: "100%",
    paddingHorizontal: 10,
    backgroundColor: "#FBE8CF",
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 10,
  },
  dropdown: {
    borderColor: "#c4d2d9",
    borderWidth: 1,
    height: 40,
    borderRadius: 12,
    paddingHorizontal: 10,
    width: "100%",
    justifyContent: "center",
    backgroundColor: "white",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  dropdownText: {
    fontSize: 16,
    color: "#fff",
  },
  datePicker: {
    borderColor: "#c4d2d9",
    borderWidth: 1,
    height: 45,
    borderRadius: 12,
    paddingHorizontal: 10,
    width: "100%",
    justifyContent: "center",
    backgroundColor: "white",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  datePickerText: {
    fontSize: 16,
    color: "#333",
  },
  button: {
    backgroundColor: "#10A78B",
    marginTop: 15,
    paddingVertical: 5,
    paddingHorizontal: 40,
    borderRadius: 30,
    alignItems: "center",
    justifyContent:"center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    height:50,
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  formTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 30,
    textAlign: "center",
  },
  filterTab: {
    padding: 7,
    margin: 5,
    borderRadius: 25,
    borderColor: '#10A78B',
    borderWidth: 1,
    backgroundColor: '#f4f4f6',
    alignItems:'center',
    justifyContent:'center',
  },
  filterTabActiveALL: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: '#10A78B',
    borderWidth: 1,
    borderColor: '#a2c3a4'
  },
  filterTabActiveRed: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: 'red',
    borderWidth: 1,
    borderColor: 'red',
  },
  filterTabActiveYellow: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: 'yellow',
    borderWidth: 1,
    borderColor: 'yellow',
  },
  filterTabActiveGreen: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: 'green',
    borderWidth: 1,
    borderColor: 'green',
  },
  inputs: {
    borderColor: "#A5D6A7",
    borderWidth: 1,
    height: 30,
    borderRadius: 14,
    width: "100%",
    paddingLeft: 5,
    backgroundColor: "#E9F7EF",
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 20,
    color: "#003366",
    fontWeight: 'regular',
    marginVertical: 30,
  },
  viewCon: {
    height: 140,
    backgroundColor: '#F4CE9C',
    borderRadius: 12,
    margin: 6.5,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3, // Dropshadow Android
    shadowColor: '#000', // Dropshadow iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  viewIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#e0f7ef',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  categoryEmoji: {
    fontSize: 30,
  },
  titleText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 4,
  },
  expiryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  expiryText: {
    fontSize: 12,
    color: '#555',
  },
  circleIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginLeft: 6,
  },
  TextInputS: { 
    padding: 8,
    borderRadius: 12,
    backgroundColor:"white",
    borderColor: '#10A78B',
    borderWidth: 1,
    marginBottom: 20,
    textAlign: 'center',
  },  
  Search: { 
    padding: 8,
    borderRadius: 12,
    backgroundColor:"white",
    borderColor: '#10A78B',
    borderWidth: 1,
    marginBottom: 20,
    textAlign: 'center',
    flexDirection: 'row',
  }, 
  errorText: {
    color: 'red',
    marginBottom: 5,
    alignSelf: 'flex-start',
    marginLeft: 2,
  },
  messageText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'red',
    textAlign: 'center',
    margin: 10,
  },
});