import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "#ffe8d6",
    flex: 1,
    paddingVertical: 50,
    alignItems: "center",
    paddingHorizontal: 30,
  },
  label: {
    textTransform: "uppercase",
    fontSize: 16,
    color: "#6b7a82",
    marginBottom: 6,
    alignSelf: "flex-start",
    fontWeight: "500",
    letterSpacing: 0.5,
  },
  formInputs: {
    borderColor: "#c4d2d9",
    borderWidth: 1,
    height: 45,
    borderRadius: 12,
    width: "100%",
    paddingHorizontal: 10,
    backgroundColor: "white",
    fontSize: 16,
    color: "#333",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 20,
  },
  dropdown: {
    borderColor: "#c4d2d9",
    borderWidth: 1,
    height: 40,
    borderRadius: 12,
    paddingHorizontal: 10,
    width: "100%",
    justifyContent: "center",
    backgroundColor: "white",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  dropdownText: {
    fontSize: 16,
    color: "#333",
  },
  datePicker: {
    borderColor: "#c4d2d9",
    borderWidth: 1,
    height: 45,
    borderRadius: 12,
    paddingHorizontal: 10,
    width: "100%",
    justifyContent: "center",
    backgroundColor: "white",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  datePickerText: {
    fontSize: 16,
    color: "#333",
  },
  button: {
    backgroundColor: "#0A7763",
    marginTop: 15,
    paddingVertical: 5,
    paddingHorizontal: 40,
    borderRadius: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    height:50,
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  formTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 30,
    textAlign: "center",
  },
  filterTab: {
    padding: 7,
    margin: 5,
    borderRadius: 25,
    borderColor: '#6FCF97',
    borderWidth: 1,
    backgroundColor: '#fff',
    alignItems:'center',
    justifyContent:'center'
  },
  filterTabActiveALL: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: '#0A7763',
    borderWidth: 1,
    borderColor: '#a2c3a4'
  },
  filterTabActiveRed: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: 'red',
    borderWidth: 1,
    borderColor: 'red',
  },
  filterTabActiveYellow: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: 'yellow',
    borderWidth: 1,
    borderColor: 'yellow',
  },
  filterTabActiveGreen: {
    padding: 10,
    margin: 5,
    borderRadius: 20,
    backgroundColor: 'green',
    borderWidth: 1,
    borderColor: 'green',
  },
  inputs: {
    borderColor: "#A5D6A7",
    borderWidth: 1,
    height: 30,
    borderRadius: 14,
    width: "100%",
    paddingLeft: 5,
    backgroundColor: "#E9F7EF",
  },
  viewCon: {
    height: 120,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderColor: "#0A7763",
    borderWidth: 0.5,
    margin: 7
  },
  viewtext: {
    flexDirection: 'row',
    height: 24,
    backgroundColor: '#eff6e0',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flex:1,
 },
  viewicon: {
    width:'100%',
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  TextInputS: { width: '100%',
    padding: 8,
    borderRadius: 25,
    borderColor: '#6FCF97',
    borderWidth: 1,
    marginBottom: 20,
    textAlign: 'center', 
    opacity: 0.7, 
  },
});